[package]
name = "cryptography-exp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
exitcode = "1.1.2"
ordered-map = "0.4.2"
regex = "1.10.3"
